### ISSUE TITLE
Make env.reset() faster

### ISSUE THREAD

**Issue by bparr** [bparr/melee-ai#8]
Running off stage until lose all stocks is too slow. Look into saved states first (since generally more useful), and then just pushing Start + Endgamebuttons.

**Comment by bparr** [comment]
I an stopping work on saved states. Here is my brain dump on them:

pyautogui.hotkey('f1') and pyautogui.hotkey('shift', 'f2 works ok when running locally. The dolphin window has to have focus though, otherwise the F1 is sent to the wrong window. This approach doesn't work on gcloud since no windowing system.

I also tried setting a controller button to map to Save and Load State hotkeys in Hotkeys.ini. Unfortunately...

[20:22] <bparr> Does the dolphin-emu-nogui build of dolphin load Config/Hotkeys.ini? I can't seem to get it to.
[20:22] <@HdkR> No
[20:23] <@HdkR> nogui doesn't hook in to the regular hotkey system at all


So it doesn't work for dolphin-emu-nogui (or headless, used on gcloud).


Next step for this bug is just to do the Start, L+R+A+Start to reset.

**Comment by deepakdilipkumar** [comment]
Tested the spam reset, seems to be working fine. Closing.
